name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - mlflow==2.8.1
    - pandas==1.5.3
    - numpy==1.24.3
    - scikit-learn==1.3.0
    - matplotlib==3.7.1
    - seaborn==0.12.2
