name: MLflow CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Manual trigger

jobs:
  ml-training:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install MLflow
      run: |
        python -m pip install --upgrade pip
        pip install mlflow
    
    - name: Run MLflow Project
      run: |
        # mlflow run MLProject --no-conda
        # Atau
        mlflow run MLProject
    
    - name: List MLflow artifacts
      run: |
        find MLProject/mlruns -type f -name "*.txt" -o -name "*.json" -o -name "*.yaml" | head -20
    
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns/
        retention-days: 30
